version: '3.8'

services:
#DB
  mysqldb:
    container_name: mysql_full-app
    image: mysql
    environment:
      MYSQL_DATABASE: mysql_full-app
      #MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3308:3306
#API
  api:
    build: . # lee el Dockerfile para crear el contenedor
    volumes:
      - .:/app
    command:
      - /bin/sh
      - -c
      - npm run start:debug
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - 4000:3000
      - 9228:9229


